name: craftcms
type: craftcms
docroot: web
php_version: "8.5"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
project_tld: test
use_dns_when_possible: true
composer_version: "2"
nodejs_version: "24"
web_environment: []
corepack_enable: false
disable_settings_management: true
disable_upload_dirs_warning: true
